### ISSUE TITLE
Is this possible to run this code in a esp32-cam to see the communication with the ov2640 sensor while capturing a photo?

### ISSUE THREAD

**Issue by FBMinis** [ok-home/logic_analyzer#2]
Also, would it be possible to run in the Arduino IDE?

**Comment by ok-home** [comment]
Yes it is possible to run on ESP32-cam.
in menuconfig you need to set ANALYZER_USE_I2S_CHANNEL_1

I didn't test the work with Arduino. everything was tested in ESP-IDF environment

**Comment by FBMinis** [comment]
I will watch some tutorials about vs code and esp-idf, then try it. i would like to be able to visualize the signal from the sccb interface. thank you

**Comment by ok-home** [comment]
Yes it is possible, but still set the i2s channel to 1 
esp32-cam uses i2s-0, logic analyzer will use i2s-1 to capture the stream.
