### ISSUE TITLE
Compiling with CMakeFile error

### ISSUE THREAD

**Issue by Duolabs** [ok-home/logic_analyzer#3]
This looks like a great project but there ain't no way to compile it it with CMake in IDF 5.0.1 in Eclipse.
I do "import" project for the example code I "Debug As" with my standard S3 configuration but it does not find the component.

Can you provide the way you make it work on your system?

Thanx

**Comment by Duolabs** [comment]
Is this repo dead?

**Comment by ok-home** [comment]
Hi I have not tested the component in Eclipse
Just re-tested in vscode, as a standard component everything works

**Comment by Duolabs** [comment]
How do you compile it step by step on eclipse then!

**Comment by ok-home** [comment]
Unfortunately, I have never used eclipse 
to connect the logic_analyzer, all you need to do is 
- copy the code to the **components** folder of the project 
- add **REQUIRES logic_analyzer** to CMakeLists.txt 
- configure the logic analyzer configuration section in menuconfig 
- call one of the interface functions ( logic_analyzer_ws_server() or logic_analyzer_cli() ).

**Comment by Duolabs** [comment]
I've tried the whole day but no luck my man...
Using IDF-5.0.1 it always requires esp_mm component which was not installed in my system.
I installed it and still many other errors are raising becuase the espressif-idf/components/esp_mm is missing files from the official repository.
I am now wondering which IDF you are using to make it work.

> configure the logic analyzer configuration section in menuconfig 

is showing up the Logic analyzer as a components but I got stuck...

Any suggestion is more than welcome and switching to VSCode (which I don't really like much) is not the solotion anyway..

Looking forward to hear from you...

**Comment by Duolabs** [comment]
managed to compile it by modifying the _components/logic_analyzer/CMakeLists.txt_ and removing esp_mm from the required libraries.

Result:
```
set(priv_require
    driver
    esp_http_server
    esp_wifi
    nvs_flash
    #esp_mm
    esp_psram
)
```

Then, it also needs to be removed from _components/logic_analyzer/logic_analyzer_hal/logic_analyzer_hal.c_:

`//#include "esp_cache.h" //esp_mm`

esp_mm does not seem to be necessary at this point as there is not reference on the code to any function used by it. This is at least what I can see from here.

At this point, something fails on the web server, and from the SDK configuration under the Logic Analyzer Configuration, I removed the flag on "Logic analyzer output data to HTTP websocket".

Some errors:
```
components/logic_analyzer/logic_analyzer_ws/logic_analyzer_ws.c:104:5: error: unknown type name 'httpd_ws_frame_t'
components/logic_analyzer/logic_analyzer_ws/logic_analyzer_ws.c:106:11: error: request for member 'type' in something not a structure or union
components/logic_analyzer/logic_analyzer_ws/logic_analyzer_ws.c:107:11: error: request for member 'payload' in something not a structure or union
components/logic_analyzer/logic_analyzer_ws/logic_analyzer_ws.c:109:11: error: implicit declaration of function 'httpd_ws_send_data' [-Werror=implicit-function-declaration]
```

It appears that we are misaligned with IDF and this is causing a tons of errors on IDF 5.0.1

I will try to run this with the limited functions of sigrok/pulseview and see what it shows up...

Any suggestion is welcome!

**Comment by ok-home** [comment]
- **esp_mm** is used in idf 5.2.x, 
without it writing to PSRAM will not work ( alas - normal cache synchronization only from this version of IDF ) 
- **httpd_ws_frame_t** 
must be enabled CONFIG_**HTTPD_WS_SUPPORT**=y in menuconfig ( sdkconfig )  - websocket support on idf httpd server 
- **sigrok/pulseview** 
I recommend using the CLI interface, it is more convenient and stable
