### ISSUE TITLE
PulseView SUMP error

### ISSUE THREAD

**Issue by Duolabs** [ok-home/logic_analyzer#4]
Finally, after a few days, I managed to compile everything in my project and use this wonderful component on the ESP32S3.

I encountered some issues using PulseView. I am analyzing the TX of a UART.

If I analyze a bin file in Raw Binary Logic Data mode with PulseView, everything is captured correctly. I tried at 115200 at 1MHz and 921600 at 5MHz, and everything is very precise.
Really wonderful!

If I try to read directly with the same configurations, I get this result where it shows that signal 0 (GPIO38 in my case) does not respond correctly and I see some spurious signals.

![PulseView_Error1](https://github.com/user-attachments/assets/f167be63-002b-4cc4-bd81-0a7fed9fcb52)

Here is my sdkconfig:

<img width="484" alt="LogiAnalyzerConfig" src="https://github.com/user-attachments/assets/3509eaf0-7403-458f-a8b4-17197e82e44a">

Can you give me some explanation for this?

**Question 1:**
What exactly do you mean by "ESP32S3 -> requires one GPIO pin not connected anywhere for PCLK signal, for sample rate less than 1 MHz - you can allow 1 LEDC channel connection"?

**Question 2:**
I am not very familiar with PulseView; is it possible to have continuous and direct streaming via the serial port without going through capture sessions (run/stop)? It might be trivial but I didn't use it much!

**Comment by Duolabs** [comment]
Finally, I understood where the problem is!

<img width="1609" alt="PulseView_OK" src="https://github.com/user-attachments/assets/b9c5363a-5901-4a09-817c-b70c0e1c89fa">


PulseView works correctly only if all 16 channels are set to active. If, as in my case, you set only 1 or 8 channels, the log is provided incorrectly, and consequently, on channel 1 (in my case), there is a continuous fluctuation of bits from 0 to 1.
Clearly, setting 16 channels, in my case, only allows me to log a maximum of 2KB, which is a significant limitation.

Any ideas on how to address this?

**Comment by ok-home** [comment]
Hi
`What exactly do you mean by "ESP32S3 -&gt; requires one GPIO pin not connected anywhere for PCLK signal, for sample rate less than 1 MHz - you can allow 1 LEDC channel connection"?`
ESP32S3 - uses a CAM module that requires an external PCLK signal (dedicated GPIO), this pin can be assigned to either the internal CLK of the CAM module or one of the LEDC channels. 
The CAM module's internal dividers are limited to 1-80 MHz, if you need a sampling rate below 1 MHz, LEDC is used.

**Comment by ok-home** [comment]
`PulseView works correctly only if all 16 channels are set to active. If, as in my case, you set only 1 or 8 channels, the log is provided incorrectly, and consequently, on channel 1 (in my case), there is a continuous fluctuation of bits from 0 to 1.
Clearly, setting 16 channels, in my case, only allows me to log a maximum of 2KB, which is a significant limitation.`

ESP32S3 - sample capture is possible only in 16/8 channel modes, this is a limitation of CAM module, so data transfer to PulseView is possible only in these modes. Direct connection to PulseView is very unstable, this is a known error of PulseView. This is exactly what the CLI interface (RawBin file) is made for. 
Memory saving - I see you have all interfaces enabled in menukonfig - disable **start WS server**, **direct connect to PulseView**, leave only **CLI** interface. If you are using ESP32S3 and you have PSRAM - I recommend to switch to esp-idf 5.2.x. Writing samples to PSRAM will become available ( sample rate up to 20 MHz - the number of samples is limited by the size of free PSRAM )

**Comment by ok-home** [comment]
`I am not very familiar with PulseView; is it possible to have continuous and direct streaming via the serial port without going through capture sessions (run/stop)? It might be trivial but I didn't use it much!`

This mode is not available in SUMP interface, it can be done separately using other interfaces of PulseView, but in this implementation of Logic Analyzer I did not implement it, this is due 
- firstly to the low speed of UART transmission (respectively limiting the frequency of samples), 
- secondly with a significantly greater impact of Logic Analyzer on the patient under study, because the patient and Logic Analyzer work on the same device.
